name: Deploy Code

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Run deployment script
        run: /home/runner/deployment-scripts/deploy-code.sh
        shell: /usr/bin/bash -e {0}
