name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    

    - name: SSH into EC2 instance 
      run: |
        ssh -i /home/runner/deployment-scripts/INTERN-pem.pem -o StrictHostKeyChecking=no admin@192.168.0.23 'echo "SSH connection successful"'
