name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    

    - name: SSH into EC2 instance through Bastion Host
      run: |
        ssh -i /home/runner/deployment-scripts/INTERN-BASTION-1.pem -o StrictHostKeyChecking=no -L 22:192.168.0.23:22 -N Administrator@10.10.1.60 &
        sleep 5
        ssh -i /home/runner/deployment-scripts/INTERN-BASTION-1.pem -o StrictHostKeyChecking=no centos@192.168.0.23 'echo "SSH connection successful"'
