name: CI/CD Pipeline Demo

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up VPN
      run: sudo /home/runner/deployment-scripts/connect-vpn.sh

    - name: Establish SSH Tunnel
      run: sudo /home/runner/deployment-scripts/connect-tunnel.sh

    - name: Deploy code
      run: sudo /home/runner/deployment-scripts/deploy-code.sh
